language: python

python:
   - "3.6"

services:
  - xvfb

install:
   - pip install coverage
   - pip install coveralls
   - pip install flake8
   - pip install nose
   - pip install -r requirements.txt

# for production, remove the --exit-zero
# this side-steps failing build on PEP8 violations
before_script:
   - "export DISPLAY=:99.0"
   - flake8 impedance --exclude=*.ipynb_checkpoints

script:
   - pytest --cov=impedance impedance/tests

after_success:
   - coverage report
   - coveralls
