language: python

python:
   - 3.6

branches:
   only:
       - master

install:
   - pip install coverage
   - pip install coveralls
   - pip install flake8
   - pip install nose
   - pip install -r requirements.txt

# for production, remove the --exit-zero
# this side-steps failing build on PEP8 violations
before_script:
   - flake8 --exit-zero codebase

script:
   - nosetests --with-coverage --cover-erase --cover-package=EISfit

after_success:
   - coverage report
   - coveralls
